server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/book_service?useTimezone=true&serverTimezone=UTC
    username: marcot
    password: senha123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3307/
    schemas: book_service
    user: marcot
    password: senha123