server:
  port: 8888
spring:
  application:
    name: greeting-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:marcotdev/greeting-config-server
          #username: username
          #password: password
          default-label: main #para encontrar a branch main no github
          search-paths:
          - 'greeting-service*'